spring:
  application:
    name: 'onesecret'
  banner:
    location: classpath:banner.txt
  datasource:
    url: "jdbc:h2:mem:onesecretdb"
    username: "one"
    password: "secret"
    driverClassName: org.h2.Driver
    jpa:
      database-platform: org.hibernate.dialect.H2Dialect
    hikari:
      minimum-idle: 1
      maximum-pool-size: 100
      idle-timeout: 60000
      pool-name: "onesecret-db-connection-pool"
      auto-commit: false
  h2:
    console:
      enabled: true
      path: /db-console
      settings.trace: false
      settings.web-allow-others: false
  flyway:
    enabled: true
    user: "one"
    password: "secret"
    schemas: "onesecretdb"
    url: "jdbc:h2:mem:onesecretdb"
    locations: filesystem:db/migration